files:
  include: '**/*.scss'
  ignore: '**/third_party/**/*.scss'
options:
  formatter: stylish
  merge-default-rules: true
rules:
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: true
  nesting-depth:
    - 2
    - max-depth: 5
  quotes:
    - 2
    - style: double
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true

  mixins-before-declarations: 2
  no-mergeable-selectors: 2
  no-trailing-whitespace: 2
  attribute-quotes: 2
  space-around-operator: 2
  space-before-colon: 2
  empty-line-between-blocks: 2

  single-line-per-selector: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  no-color-literals: 0
  no-color-keywords: 0
  no-css-comments: 0
  placeholder-in-extend: 0
  property-sort-order: 0
  pseudo-element: 0
