sudo: false
dist: trusty
language: python
branches:
  only:
    - master
python:
  - "3.5"
install:
  - "git fetch --unshallow"
  - "python bootstrap.py --setuptools-version=32.0.0"
  - "PATH=${TRAVIS_BUILD_DIR}/bin:${PATH} ./bin/buildout -c buildout-${BUILDOUT_TARGET}.cfg 2>/dev/null"
before_script:
  # setup xvfb for protractor tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "./bin/ad_check_code -a"
  - "./bin/polytester -v pyunit,pyfunc,jsunit"
  - "PATH=${TRAVIS_BUILD_DIR}/bin:${PATH} ./bin/protractor etc/protractorConfFirefox.js"
notifications:
  email: false
cache:
  directories:
  - eggs
  - node_modules
  - .cache/pip
  - .cache/bower
  - .buildout
  - parts/wheels
  - parts/rubygems
addons:
  firefox: latest-esr
env:
  matrix:
    - BUILDOUT_TARGET=meinberlin
    - BUILDOUT_TARGET=mercator
    - BUILDOUT_TARGET=spd
after_success:
  - ./bin/coveralls
